# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bellhop.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import geometry_pb2 as geometry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bellhop.proto',
  package='service',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rbellhop.proto\x12\x07service\x1a\x0egeometry.proto\"`\n\nBellhopMsg\x12(\n\rpinger_tx_loc\x18\x01 \x01(\x0b\x32\x11.geometry.Vector3\x12(\n\rpinger_rx_loc\x18\x02 \x01(\x0b\x32\x11.geometry.Vector3\" \n\nBellhopRes\x12\x12\n\npercentage\x18\x01 \x01(\x02\x32\x43\n\x07\x42\x65llhop\x12\x38\n\nBellhopSim\x12\x13.service.BellhopMsg\x1a\x13.service.BellhopRes\"\x00\x62\x06proto3'
  ,
  dependencies=[geometry__pb2.DESCRIPTOR,])




_BELLHOPMSG = _descriptor.Descriptor(
  name='BellhopMsg',
  full_name='service.BellhopMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pinger_tx_loc', full_name='service.BellhopMsg.pinger_tx_loc', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pinger_rx_loc', full_name='service.BellhopMsg.pinger_rx_loc', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=138,
)


_BELLHOPRES = _descriptor.Descriptor(
  name='BellhopRes',
  full_name='service.BellhopRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='percentage', full_name='service.BellhopRes.percentage', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=172,
)

_BELLHOPMSG.fields_by_name['pinger_tx_loc'].message_type = geometry__pb2._VECTOR3
_BELLHOPMSG.fields_by_name['pinger_rx_loc'].message_type = geometry__pb2._VECTOR3
DESCRIPTOR.message_types_by_name['BellhopMsg'] = _BELLHOPMSG
DESCRIPTOR.message_types_by_name['BellhopRes'] = _BELLHOPRES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BellhopMsg = _reflection.GeneratedProtocolMessageType('BellhopMsg', (_message.Message,), {
  'DESCRIPTOR' : _BELLHOPMSG,
  '__module__' : 'bellhop_pb2'
  # @@protoc_insertion_point(class_scope:service.BellhopMsg)
  })
_sym_db.RegisterMessage(BellhopMsg)

BellhopRes = _reflection.GeneratedProtocolMessageType('BellhopRes', (_message.Message,), {
  'DESCRIPTOR' : _BELLHOPRES,
  '__module__' : 'bellhop_pb2'
  # @@protoc_insertion_point(class_scope:service.BellhopRes)
  })
_sym_db.RegisterMessage(BellhopRes)



_BELLHOP = _descriptor.ServiceDescriptor(
  name='Bellhop',
  full_name='service.Bellhop',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=174,
  serialized_end=241,
  methods=[
  _descriptor.MethodDescriptor(
    name='BellhopSim',
    full_name='service.Bellhop.BellhopSim',
    index=0,
    containing_service=None,
    input_type=_BELLHOPMSG,
    output_type=_BELLHOPRES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BELLHOP)

DESCRIPTOR.services_by_name['Bellhop'] = _BELLHOP

# @@protoc_insertion_point(module_scope)
