// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: bellhop.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Service {
  public static partial class Bellhop
  {
    static readonly string __ServiceName = "service.Bellhop";

    static readonly grpc::Marshaller<global::Service.BellhopMsg> __Marshaller_service_BellhopMsg = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Service.BellhopMsg.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Service.BellhopRes> __Marshaller_service_BellhopRes = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Service.BellhopRes.Parser.ParseFrom);

    static readonly grpc::Method<global::Service.BellhopMsg, global::Service.BellhopRes> __Method_BellhopSim = new grpc::Method<global::Service.BellhopMsg, global::Service.BellhopRes>(
        grpc::MethodType.Unary,
        __ServiceName,
        "BellhopSim",
        __Marshaller_service_BellhopMsg,
        __Marshaller_service_BellhopRes);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Service.BellhopReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Bellhop</summary>
    [grpc::BindServiceMethod(typeof(Bellhop), "BindService")]
    public abstract partial class BellhopBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Service.BellhopRes> BellhopSim(global::Service.BellhopMsg request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Bellhop</summary>
    public partial class BellhopClient : grpc::ClientBase<BellhopClient>
    {
      /// <summary>Creates a new client for Bellhop</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public BellhopClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Bellhop that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public BellhopClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected BellhopClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected BellhopClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Service.BellhopRes BellhopSim(global::Service.BellhopMsg request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BellhopSim(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Service.BellhopRes BellhopSim(global::Service.BellhopMsg request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_BellhopSim, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Service.BellhopRes> BellhopSimAsync(global::Service.BellhopMsg request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BellhopSimAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Service.BellhopRes> BellhopSimAsync(global::Service.BellhopMsg request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_BellhopSim, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override BellhopClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new BellhopClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(BellhopBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_BellhopSim, serviceImpl.BellhopSim).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, BellhopBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_BellhopSim, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Service.BellhopMsg, global::Service.BellhopRes>(serviceImpl.BellhopSim));
    }

  }
}
#endregion
