# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: marine_acoustic.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import std_pb2 as std__pb2
import geometry_pb2 as geometry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='marine_acoustic.proto',
  package='marine_acoustic',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15marine_acoustic.proto\x12\x0fmarine_acoustic\x1a\tstd.proto\x1a\x0egeometry.proto\"`\n\x08PingInfo\x12\x11\n\tfrequency\x18\x01 \x01(\x02\x12\x13\n\x0bsound_speed\x18\x02 \x01(\x02\x12\x15\n\rtx_beamwidths\x18\x03 \x03(\x02\x12\x15\n\rrx_beamwidths\x18\x04 \x03(\x02\"W\n\x0eSonarImageData\x12\x14\n\x0cis_bigendian\x18\x01 \x01(\x08\x12\r\n\x05\x64type\x18\x02 \x01(\r\x12\x12\n\nbeam_count\x18\x03 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x04 \x03(\x0c\"\xcc\x01\n\x13ProjectedSonarImage\x12\x1b\n\x06header\x18\x01 \x01(\x0b\x32\x0b.std.Header\x12,\n\tping_info\x18\x02 \x01(\x0b\x32\x19.marine_acoustic.PingInfo\x12*\n\x0f\x62\x65\x61m_directions\x18\x03 \x03(\x0b\x32\x11.geometry.Vector3\x12\x0e\n\x06ranges\x18\x04 \x03(\x02\x12.\n\x05image\x18\x05 \x01(\x0b\x32\x1f.marine_acoustic.SonarImageDatab\x06proto3'
  ,
  dependencies=[std__pb2.DESCRIPTOR,geometry__pb2.DESCRIPTOR,])




_PINGINFO = _descriptor.Descriptor(
  name='PingInfo',
  full_name='marine_acoustic.PingInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frequency', full_name='marine_acoustic.PingInfo.frequency', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sound_speed', full_name='marine_acoustic.PingInfo.sound_speed', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tx_beamwidths', full_name='marine_acoustic.PingInfo.tx_beamwidths', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rx_beamwidths', full_name='marine_acoustic.PingInfo.rx_beamwidths', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=165,
)


_SONARIMAGEDATA = _descriptor.Descriptor(
  name='SonarImageData',
  full_name='marine_acoustic.SonarImageData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_bigendian', full_name='marine_acoustic.SonarImageData.is_bigendian', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dtype', full_name='marine_acoustic.SonarImageData.dtype', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='beam_count', full_name='marine_acoustic.SonarImageData.beam_count', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='marine_acoustic.SonarImageData.data', index=3,
      number=4, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=254,
)


_PROJECTEDSONARIMAGE = _descriptor.Descriptor(
  name='ProjectedSonarImage',
  full_name='marine_acoustic.ProjectedSonarImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='marine_acoustic.ProjectedSonarImage.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ping_info', full_name='marine_acoustic.ProjectedSonarImage.ping_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='beam_directions', full_name='marine_acoustic.ProjectedSonarImage.beam_directions', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ranges', full_name='marine_acoustic.ProjectedSonarImage.ranges', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image', full_name='marine_acoustic.ProjectedSonarImage.image', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=461,
)

_PROJECTEDSONARIMAGE.fields_by_name['header'].message_type = std__pb2._HEADER
_PROJECTEDSONARIMAGE.fields_by_name['ping_info'].message_type = _PINGINFO
_PROJECTEDSONARIMAGE.fields_by_name['beam_directions'].message_type = geometry__pb2._VECTOR3
_PROJECTEDSONARIMAGE.fields_by_name['image'].message_type = _SONARIMAGEDATA
DESCRIPTOR.message_types_by_name['PingInfo'] = _PINGINFO
DESCRIPTOR.message_types_by_name['SonarImageData'] = _SONARIMAGEDATA
DESCRIPTOR.message_types_by_name['ProjectedSonarImage'] = _PROJECTEDSONARIMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PingInfo = _reflection.GeneratedProtocolMessageType('PingInfo', (_message.Message,), {
  'DESCRIPTOR' : _PINGINFO,
  '__module__' : 'marine_acoustic_pb2'
  # @@protoc_insertion_point(class_scope:marine_acoustic.PingInfo)
  })
_sym_db.RegisterMessage(PingInfo)

SonarImageData = _reflection.GeneratedProtocolMessageType('SonarImageData', (_message.Message,), {
  'DESCRIPTOR' : _SONARIMAGEDATA,
  '__module__' : 'marine_acoustic_pb2'
  # @@protoc_insertion_point(class_scope:marine_acoustic.SonarImageData)
  })
_sym_db.RegisterMessage(SonarImageData)

ProjectedSonarImage = _reflection.GeneratedProtocolMessageType('ProjectedSonarImage', (_message.Message,), {
  'DESCRIPTOR' : _PROJECTEDSONARIMAGE,
  '__module__' : 'marine_acoustic_pb2'
  # @@protoc_insertion_point(class_scope:marine_acoustic.ProjectedSonarImage)
  })
_sym_db.RegisterMessage(ProjectedSonarImage)


# @@protoc_insertion_point(module_scope)
