// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: sensor.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Sensor {

  /// <summary>Holder for reflection information generated from sensor.proto</summary>
  public static partial class SensorReflection {

    #region Descriptor
    /// <summary>File descriptor for sensor.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SensorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxzZW5zb3IucHJvdG8SBnNlbnNvchoJc3RkLnByb3RvGg5nZW9tZXRyeS5w",
            "cm90byKQAgoDSW11EhsKBmhlYWRlchgBIAEoCzILLnN0ZC5IZWFkZXISKQoL",
            "b3JpZW50YXRpb24YAiABKAsyFC5nZW9tZXRyeS5RdWF0ZXJuaW9uEh0KFW9y",
            "aWVudGF0aW9uQ292YXJpYW5jZRgDIAMoARIqCg9hbmd1bGFyVmVsb2NpdHkY",
            "BCABKAsyES5nZW9tZXRyeS5WZWN0b3IzEiEKGWFuZ3VsYXJWZWxvY2l0eUNv",
            "dmFyaWFuY2UYBSADKAESLQoSbGluZWFyQWNjZWxlcmF0aW9uGAYgASgLMhEu",
            "Z2VvbWV0cnkuVmVjdG9yMxIkChxsaW5lYXJBY2NlbGVyYXRpb25Db3Zhcmlh",
            "bmNlGAcgAygBYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Std.StdReflection.Descriptor, global::Geometry.GeometryReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Sensor.Imu), global::Sensor.Imu.Parser, new[]{ "Header", "Orientation", "OrientationCovariance", "AngularVelocity", "AngularVelocityCovariance", "LinearAcceleration", "LinearAccelerationCovariance" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Imu : pb::IMessage<Imu> {
    private static readonly pb::MessageParser<Imu> _parser = new pb::MessageParser<Imu>(() => new Imu());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Imu> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Sensor.SensorReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Imu() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Imu(Imu other) : this() {
      header_ = other.header_ != null ? other.header_.Clone() : null;
      orientation_ = other.orientation_ != null ? other.orientation_.Clone() : null;
      orientationCovariance_ = other.orientationCovariance_.Clone();
      angularVelocity_ = other.angularVelocity_ != null ? other.angularVelocity_.Clone() : null;
      angularVelocityCovariance_ = other.angularVelocityCovariance_.Clone();
      linearAcceleration_ = other.linearAcceleration_ != null ? other.linearAcceleration_.Clone() : null;
      linearAccelerationCovariance_ = other.linearAccelerationCovariance_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Imu Clone() {
      return new Imu(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    private global::Std.Header header_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Std.Header Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "orientation" field.</summary>
    public const int OrientationFieldNumber = 2;
    private global::Geometry.Quaternion orientation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Geometry.Quaternion Orientation {
      get { return orientation_; }
      set {
        orientation_ = value;
      }
    }

    /// <summary>Field number for the "orientationCovariance" field.</summary>
    public const int OrientationCovarianceFieldNumber = 3;
    private static readonly pb::FieldCodec<double> _repeated_orientationCovariance_codec
        = pb::FieldCodec.ForDouble(26);
    private readonly pbc::RepeatedField<double> orientationCovariance_ = new pbc::RepeatedField<double>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<double> OrientationCovariance {
      get { return orientationCovariance_; }
    }

    /// <summary>Field number for the "angularVelocity" field.</summary>
    public const int AngularVelocityFieldNumber = 4;
    private global::Geometry.Vector3 angularVelocity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Geometry.Vector3 AngularVelocity {
      get { return angularVelocity_; }
      set {
        angularVelocity_ = value;
      }
    }

    /// <summary>Field number for the "angularVelocityCovariance" field.</summary>
    public const int AngularVelocityCovarianceFieldNumber = 5;
    private static readonly pb::FieldCodec<double> _repeated_angularVelocityCovariance_codec
        = pb::FieldCodec.ForDouble(42);
    private readonly pbc::RepeatedField<double> angularVelocityCovariance_ = new pbc::RepeatedField<double>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<double> AngularVelocityCovariance {
      get { return angularVelocityCovariance_; }
    }

    /// <summary>Field number for the "linearAcceleration" field.</summary>
    public const int LinearAccelerationFieldNumber = 6;
    private global::Geometry.Vector3 linearAcceleration_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Geometry.Vector3 LinearAcceleration {
      get { return linearAcceleration_; }
      set {
        linearAcceleration_ = value;
      }
    }

    /// <summary>Field number for the "linearAccelerationCovariance" field.</summary>
    public const int LinearAccelerationCovarianceFieldNumber = 7;
    private static readonly pb::FieldCodec<double> _repeated_linearAccelerationCovariance_codec
        = pb::FieldCodec.ForDouble(58);
    private readonly pbc::RepeatedField<double> linearAccelerationCovariance_ = new pbc::RepeatedField<double>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<double> LinearAccelerationCovariance {
      get { return linearAccelerationCovariance_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Imu);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Imu other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Header, other.Header)) return false;
      if (!object.Equals(Orientation, other.Orientation)) return false;
      if(!orientationCovariance_.Equals(other.orientationCovariance_)) return false;
      if (!object.Equals(AngularVelocity, other.AngularVelocity)) return false;
      if(!angularVelocityCovariance_.Equals(other.angularVelocityCovariance_)) return false;
      if (!object.Equals(LinearAcceleration, other.LinearAcceleration)) return false;
      if(!linearAccelerationCovariance_.Equals(other.linearAccelerationCovariance_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (header_ != null) hash ^= Header.GetHashCode();
      if (orientation_ != null) hash ^= Orientation.GetHashCode();
      hash ^= orientationCovariance_.GetHashCode();
      if (angularVelocity_ != null) hash ^= AngularVelocity.GetHashCode();
      hash ^= angularVelocityCovariance_.GetHashCode();
      if (linearAcceleration_ != null) hash ^= LinearAcceleration.GetHashCode();
      hash ^= linearAccelerationCovariance_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (orientation_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Orientation);
      }
      orientationCovariance_.WriteTo(output, _repeated_orientationCovariance_codec);
      if (angularVelocity_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(AngularVelocity);
      }
      angularVelocityCovariance_.WriteTo(output, _repeated_angularVelocityCovariance_codec);
      if (linearAcceleration_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(LinearAcceleration);
      }
      linearAccelerationCovariance_.WriteTo(output, _repeated_linearAccelerationCovariance_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (header_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      if (orientation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Orientation);
      }
      size += orientationCovariance_.CalculateSize(_repeated_orientationCovariance_codec);
      if (angularVelocity_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AngularVelocity);
      }
      size += angularVelocityCovariance_.CalculateSize(_repeated_angularVelocityCovariance_codec);
      if (linearAcceleration_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LinearAcceleration);
      }
      size += linearAccelerationCovariance_.CalculateSize(_repeated_linearAccelerationCovariance_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Imu other) {
      if (other == null) {
        return;
      }
      if (other.header_ != null) {
        if (header_ == null) {
          header_ = new global::Std.Header();
        }
        Header.MergeFrom(other.Header);
      }
      if (other.orientation_ != null) {
        if (orientation_ == null) {
          orientation_ = new global::Geometry.Quaternion();
        }
        Orientation.MergeFrom(other.Orientation);
      }
      orientationCovariance_.Add(other.orientationCovariance_);
      if (other.angularVelocity_ != null) {
        if (angularVelocity_ == null) {
          angularVelocity_ = new global::Geometry.Vector3();
        }
        AngularVelocity.MergeFrom(other.AngularVelocity);
      }
      angularVelocityCovariance_.Add(other.angularVelocityCovariance_);
      if (other.linearAcceleration_ != null) {
        if (linearAcceleration_ == null) {
          linearAcceleration_ = new global::Geometry.Vector3();
        }
        LinearAcceleration.MergeFrom(other.LinearAcceleration);
      }
      linearAccelerationCovariance_.Add(other.linearAccelerationCovariance_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (header_ == null) {
              header_ = new global::Std.Header();
            }
            input.ReadMessage(header_);
            break;
          }
          case 18: {
            if (orientation_ == null) {
              orientation_ = new global::Geometry.Quaternion();
            }
            input.ReadMessage(orientation_);
            break;
          }
          case 26:
          case 25: {
            orientationCovariance_.AddEntriesFrom(input, _repeated_orientationCovariance_codec);
            break;
          }
          case 34: {
            if (angularVelocity_ == null) {
              angularVelocity_ = new global::Geometry.Vector3();
            }
            input.ReadMessage(angularVelocity_);
            break;
          }
          case 42:
          case 41: {
            angularVelocityCovariance_.AddEntriesFrom(input, _repeated_angularVelocityCovariance_codec);
            break;
          }
          case 50: {
            if (linearAcceleration_ == null) {
              linearAcceleration_ = new global::Geometry.Vector3();
            }
            input.ReadMessage(linearAcceleration_);
            break;
          }
          case 58:
          case 57: {
            linearAccelerationCovariance_.AddEntriesFrom(input, _repeated_linearAccelerationCovariance_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
