# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import std_pb2 as std__pb2
import geometry_pb2 as geometry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensor.proto',
  package='sensor',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0csensor.proto\x12\x06sensor\x1a\tstd.proto\x1a\x0egeometry.proto\"\x90\x02\n\x03Imu\x12\x1b\n\x06header\x18\x01 \x01(\x0b\x32\x0b.std.Header\x12)\n\x0borientation\x18\x02 \x01(\x0b\x32\x14.geometry.Quaternion\x12\x1d\n\x15orientationCovariance\x18\x03 \x03(\x01\x12*\n\x0f\x61ngularVelocity\x18\x04 \x01(\x0b\x32\x11.geometry.Vector3\x12!\n\x19\x61ngularVelocityCovariance\x18\x05 \x03(\x01\x12-\n\x12linearAcceleration\x18\x06 \x01(\x0b\x32\x11.geometry.Vector3\x12$\n\x1clinearAccelerationCovariance\x18\x07 \x03(\x01\x62\x06proto3')
  ,
  dependencies=[std__pb2.DESCRIPTOR,geometry__pb2.DESCRIPTOR,])




_IMU = _descriptor.Descriptor(
  name='Imu',
  full_name='sensor.Imu',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='sensor.Imu.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='sensor.Imu.orientation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orientationCovariance', full_name='sensor.Imu.orientationCovariance', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angularVelocity', full_name='sensor.Imu.angularVelocity', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angularVelocityCovariance', full_name='sensor.Imu.angularVelocityCovariance', index=4,
      number=5, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='linearAcceleration', full_name='sensor.Imu.linearAcceleration', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='linearAccelerationCovariance', full_name='sensor.Imu.linearAccelerationCovariance', index=6,
      number=7, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=324,
)

_IMU.fields_by_name['header'].message_type = std__pb2._HEADER
_IMU.fields_by_name['orientation'].message_type = geometry__pb2._QUATERNION
_IMU.fields_by_name['angularVelocity'].message_type = geometry__pb2._VECTOR3
_IMU.fields_by_name['linearAcceleration'].message_type = geometry__pb2._VECTOR3
DESCRIPTOR.message_types_by_name['Imu'] = _IMU
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Imu = _reflection.GeneratedProtocolMessageType('Imu', (_message.Message,), dict(
  DESCRIPTOR = _IMU,
  __module__ = 'sensor_pb2'
  # @@protoc_insertion_point(class_scope:sensor.Imu)
  ))
_sym_db.RegisterMessage(Imu)


# @@protoc_insertion_point(module_scope)
