// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: simulation_control.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Simulatoncontrol {
  public static partial class SimulationControl
  {
    static readonly string __ServiceName = "simulatoncontrol.SimulationControl";

    static readonly grpc::Marshaller<global::Simulatoncontrol.StepRequest> __Marshaller_simulatoncontrol_StepRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Simulatoncontrol.StepRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Simulatoncontrol.StepResponse> __Marshaller_simulatoncontrol_StepResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Simulatoncontrol.StepResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Simulatoncontrol.SetStartTimeRequest> __Marshaller_simulatoncontrol_SetStartTimeRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Simulatoncontrol.SetStartTimeRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Simulatoncontrol.SetStartTimeResponse> __Marshaller_simulatoncontrol_SetStartTimeResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Simulatoncontrol.SetStartTimeResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Simulatoncontrol.StepRequest, global::Simulatoncontrol.StepResponse> __Method_Step = new grpc::Method<global::Simulatoncontrol.StepRequest, global::Simulatoncontrol.StepResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Step",
        __Marshaller_simulatoncontrol_StepRequest,
        __Marshaller_simulatoncontrol_StepResponse);

    static readonly grpc::Method<global::Simulatoncontrol.SetStartTimeRequest, global::Simulatoncontrol.SetStartTimeResponse> __Method_SetStartTime = new grpc::Method<global::Simulatoncontrol.SetStartTimeRequest, global::Simulatoncontrol.SetStartTimeResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetStartTime",
        __Marshaller_simulatoncontrol_SetStartTimeRequest,
        __Marshaller_simulatoncontrol_SetStartTimeResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Simulatoncontrol.SimulationControlReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of SimulationControl</summary>
    public abstract partial class SimulationControlBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Simulatoncontrol.StepResponse> Step(global::Simulatoncontrol.StepRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Simulatoncontrol.SetStartTimeResponse> SetStartTime(global::Simulatoncontrol.SetStartTimeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for SimulationControl</summary>
    public partial class SimulationControlClient : grpc::ClientBase<SimulationControlClient>
    {
      /// <summary>Creates a new client for SimulationControl</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public SimulationControlClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SimulationControl that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public SimulationControlClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected SimulationControlClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected SimulationControlClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Simulatoncontrol.StepResponse Step(global::Simulatoncontrol.StepRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Step(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Simulatoncontrol.StepResponse Step(global::Simulatoncontrol.StepRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Step, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Simulatoncontrol.StepResponse> StepAsync(global::Simulatoncontrol.StepRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StepAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Simulatoncontrol.StepResponse> StepAsync(global::Simulatoncontrol.StepRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Step, null, options, request);
      }
      public virtual global::Simulatoncontrol.SetStartTimeResponse SetStartTime(global::Simulatoncontrol.SetStartTimeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetStartTime(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Simulatoncontrol.SetStartTimeResponse SetStartTime(global::Simulatoncontrol.SetStartTimeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetStartTime, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Simulatoncontrol.SetStartTimeResponse> SetStartTimeAsync(global::Simulatoncontrol.SetStartTimeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetStartTimeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Simulatoncontrol.SetStartTimeResponse> SetStartTimeAsync(global::Simulatoncontrol.SetStartTimeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetStartTime, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override SimulationControlClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SimulationControlClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(SimulationControlBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Step, serviceImpl.Step)
          .AddMethod(__Method_SetStartTime, serviceImpl.SetStartTime).Build();
    }

  }
}
#endregion
