# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import visualization_pb2 as visualization__pb2


class VisualizationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetMarker = channel.unary_stream(
                '/visualization.Visualization/SetMarker',
                request_serializer=visualization__pb2.MarkerRequest.SerializeToString,
                response_deserializer=visualization__pb2.Marker.FromString,
                )
        self.SetMarkerArray = channel.unary_stream(
                '/visualization.Visualization/SetMarkerArray',
                request_serializer=visualization__pb2.MarkerRequest.SerializeToString,
                response_deserializer=visualization__pb2.MarkerArray.FromString,
                )


class VisualizationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetMarker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMarkerArray(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VisualizationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetMarker': grpc.unary_stream_rpc_method_handler(
                    servicer.SetMarker,
                    request_deserializer=visualization__pb2.MarkerRequest.FromString,
                    response_serializer=visualization__pb2.Marker.SerializeToString,
            ),
            'SetMarkerArray': grpc.unary_stream_rpc_method_handler(
                    servicer.SetMarkerArray,
                    request_deserializer=visualization__pb2.MarkerRequest.FromString,
                    response_serializer=visualization__pb2.MarkerArray.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'visualization.Visualization', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Visualization(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetMarker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/visualization.Visualization/SetMarker',
            visualization__pb2.MarkerRequest.SerializeToString,
            visualization__pb2.Marker.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetMarkerArray(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/visualization.Visualization/SetMarkerArray',
            visualization__pb2.MarkerRequest.SerializeToString,
            visualization__pb2.MarkerArray.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
